### ISSUE TITLE
Checklist items for lecture 1

### ISSUE THREAD

**Issue by rudymatela** [AronKG/Group-1#11]
Create a project hosted on GitHub with a markdown file
with a draft of a project plan.

Checklist:

* [x] Group of five students organized and recorded on Canvas.
* [x] Git: `name` and `email` set in `.gitconfig` properly for all 5 students.
* [x] Git: changes tracket through `git`.
* [x] `README.md` with a project description.
* [x] GitHub: project hosted on GitHub.
* [x] GitHub: GitHub repository shared with Tuwe ([`tuvelofstrom`]) and Rudy ([`rudymatela`]).
* [x] GitHub: GitHub repository link sent to both Tuwe and Rudy by email or Canvas.
* [x] `README.md` with a table/list of the 5 group members and their GitHub handles
* [x] `README.md`: Declaration section built with an associated commit from each of the students. (See below)
* [x] `README.md`: proper markdown with headings / etc.
* [x] `README.md` with plan: What will you implement?  How will it work?  What kind of features will it have?
* [x] `README.md` with plan: which language(s) will you use?
* [x] `README.md` with plan: what build system will you use?
* [x] Git: at least one commit from each student in the group.
* [x] no force pushes to `master`/`main` (if you need to undo changes, use a __new commit__).
