### ISSUE TITLE
Checklist item for lecture 3 

### ISSUE THREAD

**Issue by AronKG** [AronKG/Group-1#27]
* [x]  Add a .gitignore file to your project
* [x]  Has a revert commit (don’t edit history: create a new revert commit!).
* [x]  Has a branch implementing a small feature.
* [x]  Has a merge commit (of the branch)
* [x]  Has a branch in conflict with main/master 
* [x]  Try to merge and resolve the merge conflict
* [x]  Has working compilation and running instructions in the README.
* [x]  Has issues associated with each of your changes.
