### ISSUE TITLE
Checklist items for lecture 4

### ISSUE THREAD

**Issue by 11Johan11** [AronKG/Group-1#28]
- [x] Has a unit test.
- [x] #48
- [x] #49
- [x] README with instructions of how to run the unit tests.
- [x] README with instructions of how to generate code coverage information for your unit tests
- [x] README with instructions of how to run a linter for your project
- [x] If you are using assets found online as part of your project, please explicitly list these on the README.
