### ISSUE TITLE
Lecture 6 checklist: PRs & Review

### ISSUE THREAD

**Issue by rudymatela** [AronKG/Group-1#69]
Start using pull requests and doing code review in your project. Use this while you carry on with your project implementation.

Checklist:

* [x] Your project has pull requests and code review.
* [x] Each student has created at least one pull request.
* [x] Each student has performed at least one code review.
* [x] Each student has merged his own pull request after the code review.
* [x] `main` is passing / green. (and should be always from now on!)
