### ISSUE TITLE
checklist 7

### ISSUE THREAD

**Issue by AronKG** [AronKG/Group-1#70]
1. [x] Make your first release v0.1.0 by creating a tag through git.
2. [x] Generate [an artifact](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts) through CI.  This can be anything that makes sense to your project: an executable file, a code coverage report, an installer 
   for the built version, etc.
3. [x] Carry on with your implementation adding more features to your project: use issues and PRs to track your work.
4. [ ] (Optional) (if your project is a "desktop" project, you may choose to do this if you like) When a commit is tagged with a version 
    (v0.1.2), a release artifact is generated: this may be a simple executable or an installer
5. [ ] (Optional) (if your project is a "web" project, you may choose to do this if you like) When a commit is tagged with a version (v0.1.2), the application is deployed on a (testing) server
