### ISSUE TITLE
Lecture 9 checklist

### ISSUE THREAD

**Issue by MohamadAlkhaled** [AronKG/Group-1#83]
- [x] Create an issue titled "Lecture 9 checklist" to track these checklist items
- [x] Carry on with your implementation adding more features to your project: use issues and PRs to track your work; add unit tests when appropriate.
- [x] List the issues and PRs you worked on during the week in the "Lecture 9 checklist" issue.
- [x] Define a few project goals for the upcoming weeks, create them as issues, list them in the "Lecture 9 checklist" issue.
- [x] Make a new release following Semantic Versioning rules.
