### ISSUE TITLE
Lecture 10 checklist

### ISSUE THREAD

**Issue by MohamadAlkhaled** [AronKG/Group-1#92]
- [x] create an issue titled "Lecture 10 checklist" to track these checklist items
- [ ] each student has created at least two to five unit tests with matching PRs and code review
- [x] project has at least one of the following types of tests:
       * Integration tests
       * Nonfunctional tests (e.g.: performance, capacity)
       * Property tests
- [ ] code coverage of tests is increased by at least 20%.  List the "starting" and "ending" commits in the "Lecture 10 checklist" 
    issue with the achieved percentage increase.
- [x] main is still passing / green. (and should be always from now on!)

**Comment by HenrikEriksson1** [comment]
- [ ] hehhe

**Comment by rudymatela** [comment]
> Can you please link to the PRs where the integration tests are implemented? (The PR identifiers)

I can see that integration tests through Selenium have been added to your project now.  Thanks for adding it.

**Comment by 11Johan11** [comment]
@danieljohansson94
