### ISSUE TITLE
Lecture 11 checklist

### ISSUE THREAD

**Issue by MohamadAlkhaled** [AronKG/Group-1#99]
- [x] create an issue titled "Lecture 11 checklist" to track these checklist items
- [x] Carry on with your implementation adding more features to your project: use issues and PRs to track your work.
- [x] set your final project goals as issues, link them from the "Lecture 11 checklist"
